### ISSUE TITLE
Is it possible to allow mismatches?

### ISSUE THREAD

**Issue by Yyeserin** [Molmed/fastq_demux#11]
Hello,

I wonder if the software allows some mismatches between the barcodes in the list and on the headers? E.g. allowing 1 bp mismatch? I couldn't see such an option on the website. But maybe it is there.

Best,
Yeserin.

**Comment by b97pla** [comment]
Hi!

Yes, it is now possible to allow mismatches in the index. Just use the `--mismatches N` parameter, where `N` is the number of mismatches to allow. Note that you will get an exception in case there are index collisions as a consequence.

See also `fastq_demux --help`
